[versions]
kotlin = "2.1.21"
okio = "3.15.0"

junit5 = "5.10.0"
kotest = "5.6.1"
kover = "0.9.1"

dokka = "2.0.0"
maven-publish = "0.30.0"
spotless = "6.25.0"
versions = "0.52.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }

[libraries]
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
testing-kotest = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
