[versions]
kotlin = "1.6.10"
okio = "2.10.0"
kotlin-xml-builder = "1.9.0"
ktlint = "0.46.0"
kotest = "5.0.3"
spotless = "6.18.0"
versions = "0.46.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
testing-kotest = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-xml-builder = { module = "org.redundent:kotlin-xml-builder", version.ref = "kotlin-xml-builder" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
